# Generated by Django 5.0.6 on 2026-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_concession', models.CharField(choices=[('TEMPORAIRE', 'Temporaire'), ('PERPETUELLE', 'Perpetuelle'), ('RENOUVELABLE', 'Renouvelable')], default='TEMPORAIRE', max_length=20)),
                ('duree_annees', models.IntegerField(default=5)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('renouvelable', models.BooleanField(default=True)),
                ('date_renouvellement', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concession',
                'verbose_name_plural': 'Concessions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_prevue', models.DateField()),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande en cours'), ('APPROUVEE', 'Approuvee'), ('REFUSEE', 'Refusee'), ('REALISEE', 'Realisee')], default='DEMANDE', max_length=20)),
                ('motif', models.TextField()),
                ('autorisation_pdf', models.FileField(blank=True, null=True, upload_to='exhumations/autorisations/')),
                ('proces_verbal', models.TextField(blank=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exhumation',
                'verbose_name_plural': 'Exhumations',
                'ordering': ['-date_demande'],
            },
        ),
    ]
