# Generated by Django 5.0.6 on 2026-06-23 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concessions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exhumation',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_approuvees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='concession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to='concessions.concession'),
        ),
    ]
