# Generated by Django 5.0.6 on 2026-06-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_mfa_code_user_mfa_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_expediteur',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mot_de_passe_expediteur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
