# Generated by Django 5.0.6 on 2026-06-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nombre_caveaux', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='terrains.zone')),
            ],
            options={
                'verbose_name': 'Bloc',
                'verbose_name_plural': 'Blocs',
            },
        ),
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Reserve'), ('OCCUPE', 'Occupe')], default='DISPONIBLE', max_length=20)),
                ('longueur', models.FloatField(default=2.5)),
                ('largeur', models.FloatField(default=1.0)),
                ('superficie', models.FloatField(default=2.5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caveaux', to='terrains.bloc')),
            ],
            options={
                'verbose_name': 'Caveau',
                'verbose_name_plural': 'Caveaux',
                'unique_together': {('bloc', 'numero')},
            },
        ),
    ]
