# Generated by Django 5.0.6 on 2026-06-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField()),
                ('date_enterrement', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('observations', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Defunt',
                'verbose_name_plural': 'Defunts',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Valide'), ('ANNULE', 'Annule')], default='EN_ATTENTE', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='terrains.caveau')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
