# Generated by Django 5.0.6 on 2026-06-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defunt',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='defunt',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defunt',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
